<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="58624" started-at="2017-12-18T12:26:05Z" finished-at="2017-12-18T12:27:03Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="58624" started-at="2017-12-18T12:26:05Z" finished-at="2017-12-18T12:27:03Z">
      <class name="pom.LoginToFacebook">
        <test-method status="FAIL" signature="loginToFB(java.lang.String, java.lang.String)[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="loginToFB" duration-ms="15969" started-at="2017-12-18T17:56:05Z" data-provider="FbData" finished-at="2017-12-18T17:56:21Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manager]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Correct email or password expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Correct email or password expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertFalse(Assert.java:65)at pom.LoginToFacebook.loginToFB(LoginToFacebook.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToFB -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="tearDown" is-config="true" duration-ms="354" started-at="2017-12-18T17:56:21Z" finished-at="2017-12-18T17:56:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="loginToFB(java.lang.String, java.lang.String)[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="loginToFB" duration-ms="22775" started-at="2017-12-18T17:56:21Z" data-provider="FbData" finished-at="2017-12-18T17:56:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[jadhavpooja103@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[saminprachi]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToFB -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="tearDown" is-config="true" duration-ms="417" started-at="2017-12-18T17:56:44Z" finished-at="2017-12-18T17:56:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="loginToFB(java.lang.String, java.lang.String)[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="loginToFB" duration-ms="18737" started-at="2017-12-18T17:56:44Z" data-provider="FbData" finished-at="2017-12-18T17:57:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[admin2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[manager2]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Correct email or password expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Correct email or password expected [false] but found [true]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertFalse(Assert.java:65)at pom.LoginToFacebook.loginToFB(LoginToFacebook.java:33)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToFB -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:pom.LoginToFacebook@30a3107a]" name="tearDown" is-config="true" duration-ms="335" started-at="2017-12-18T17:57:03Z" finished-at="2017-12-18T17:57:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- pom.LoginToFacebook -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
